name: Build and deploy browser examples

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build:browser
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages # The branch the action should deploy to.
          # Re-enable when v5 is in develop
          # clean: true
          folder: examples/browser/web # The folder the action should deploy.
          ssh-key: ${{ secrets.DEPLOY_KEY }}
