name: Build docs and deploy

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build-docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages # The branch the action should deploy to.
          clean: true
          folder: docs # The folder the action should deploy.
          ssh-key: ${{ secrets.DEPLOY_KEY }}
