# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.4.0
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm install --frozen-lockfile
    - run: npm run test
      env:
        CI: true
    - run: npm run build
    - run: npm run no-git-changes
